module.exports = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.js"],
  testMatch: ["<rootDir>/src/**/*.test.{js,jsx}"],
  moduleNameMapper: {
    "\\.(css|less|scss|sass)$": "<rootDir>/src/test/styleMock.js",
  },
  transform: {
    "^.+\\.[jt]sx?$": "babel-jest",
  },
  collectCoverageFrom: [
    "src/**/*.{js,jsx}",
    "!src/main.jsx",
    "!src/**/*.test.{js,jsx}",
    "!src/test/**",
    "!src/components/user/ui/**",
    "!src/components/user/preview/LivePreview.jsx",
    "!src/components/user/workspace/ChallengeChat.jsx",
    "!src/components/user/workspace/ReactWorkspace.jsx",
    "!src/components/user/workspace/SharedChallengeEditorLayout.jsx",
    "!src/components/user/workspace/UnifiedCodeWorkspace.jsx",
    "!src/components/user/workspace/useSharedChallengeEditorState.js",
    "!src/components/user/galaxy/GalaxyView.jsx",
    "!src/components/user/galaxy/Planet.jsx",
    "!src/components/user/galaxy/GalaxySelect.jsx",
    "!src/components/user/galaxy/galaxyData.js",
    "!src/components/user/test/TestInterface.jsx",
    "!src/components/user/UserLayout.jsx",
    "!src/components/admin/Challenges.jsx",
    "!src/components/admin/ChallengeEditModal.jsx",
    "!src/components/admin/Dashboard.jsx",
    "!src/components/admin/Reports.jsx",
    "!src/components/sme/SMEDashboardHome.jsx",
    "!src/pages/user/Dashboard.jsx",
    "!src/pages/user/ChallengeDetail.jsx",
    "!src/pages/user/CodeOfTheDay.jsx",
    "!src/pages/user/Reports.jsx",
    "!src/pages/user/Test.jsx",
    "!src/pages/public/UnauthorizedPage.jsx",
    "!src/components/layout/**",
    "!src/services/userService.js",
  ],
};
